test: Pin factory-boy to v2.4
Locally (with factory-boy 2.12.0), tests failed with this error:

 FactoryError: Cannot generate instances of abstract factory Resource; Ensure Resource.Meta.model is set and Resource.Meta.abstract is either not set or False.

On Github, v2.4 is installed and we don't get this error. Probably we should update the tests to work with the latest version, but right now I would like to finish replacing messytables with tabulator, and worry about that later.